// Injected test helper (ashley TEST set). Upstream: ashley/tests/com/badlogic/ashley/core/ComponentClassFactory.java
// (the mechanical translation, kept verbatim below, except the PARENT LOADER). Java's
// `class ComponentClassFactory extends ClassLoader` takes the SYSTEM class loader as parent, which
// under gradle holds the application classes; under sbt's forked test JVM they live in a child
// loader, so this instead takes the loader that defined this class.

/*
 * Generated by Baltic Porter 0.1.0-SNAPSHOT — DO NOT EDIT; regenerate instead.
 *
 * Ported from: ashley/tests/com/badlogic/ashley/core/ComponentClassFactory.java
 * Original license: Apache-2.0 (see Ashley upstream)
 * upstream-commit: ashley@d63d542228cd8c62cc2f7adf20055b0ac59a547e (last change to ashley/tests; origin https://github.com/libgdx/ashley.git)
 */

/* porter: renamed-package reason=configured phase=package-rename key="com.badlogic.ashley.core -> sge.ecs" from=com.badlogic.ashley.core.ComponentClassFactory to=sge.ecs.ComponentClassFactory */
package sge.ecs

/** Class loader allowing dynamic {@link Component} class definitions. */
class ComponentClassFactory extends java.lang.ClassLoader(classOf[ComponentClassFactory].getClassLoader) {

  /** create new {@link Component} type
    * @param name
    *   name of the class to create
    * @return
    *   created class */
  @java.lang.SuppressWarnings(scala.Array[java.lang.String]("unchecked"))
  def createComponentType(name: java.lang.String): java.lang.Class[? <: sge.ecs.Component] = {
    val cw:            org.mockito.asm.ClassWriter = new org.mockito.asm.ClassWriter(org.mockito.asm.ClassWriter.COMPUTE_FRAMES)
    val interfacePath: java.lang.String            = classOf[sge.ecs.Component].getName().replaceAll("\\.", "/")
    // create public class (default package) implementing Component
    // Java 1.6
    // public class
    // package and name
    // signature (null means not generic)
    cw.visit(
      org.mockito.asm.Opcodes.V1_6,
      org.mockito.asm.Opcodes.ACC_PUBLIC,
      name,
      null,
      "java/lang/Object",
      scala.Array[java.lang.String](interfacePath)
    )
    // create public no-arg constructor
    // exceptions (array of strings)
    // public method
    // method name
    // descriptor
    val con: org.mockito.asm.MethodVisitor = cw.visitMethod(org.mockito.asm.Opcodes.ACC_PUBLIC, "<init>", "()V", null, null)
    // define constructor body : call super constructor (java.lang.Object)
    con.visitCode()
    // Start the code for this method
    con.visitVarInsn(org.mockito.asm.Opcodes.ALOAD, 0)
    // Load "this" onto the stack
    // Invoke an instance method (non-virtual)
    // Class on which the method is defined
    // Name of the method
    con.visitMethodInsn(org.mockito.asm.Opcodes.INVOKESPECIAL, "java/lang/Object", "<init>", "()V")
    // Descriptor
    con.visitInsn(org.mockito.asm.Opcodes.RETURN)
    // End the constructor method
    // Specify max stack and local vars
    con.visitMaxs(1, 1)
    // close class definition.
    cw.visitEnd()
    // load and return class.
    val b: scala.Array[scala.Byte] = cw.toByteArray()
    return this.defineClass(name, b, 0, b.length).asInstanceOf[java.lang.Class[? <: sge.ecs.Component]]
  }
}
